### PR TITLE
deps: update nix to 0.9

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by Detegr** [comment]
Please run `rustfmt-nightly` for the source code and fix the Windows build, thanks!

**Comment by equal-l2** [comment]
The build error on Windows fixed with #36.
@ignatenkobrain Now, all you have to do is to run `rustfmt-nightly`!

**Comment by ignatenkobrain** [comment]
let's see now.

**Comment by ignatenkobrain** [comment]
@Detegr @equal-l2 should be good to merge

**Comment by Detegr** [comment]
Thanks!

**Pull request merged**
