### PR TITLE
Update nix dependency

### PR DESCRIPTION
**Pull request by kornelski**

### CODE REVIEW

**Comment by jonhoo** [comment]
A gentle ping to @Detegr on this in case you don't have watching enabled :)

**Comment by Detegr** [comment]
Is there a problem with `nix 0.14` or is this just for keeping things up to date? I am asking because I'm not sure if I should release a new version just to keep `nix` dependency up-do-date?

**Comment by kornelski** [comment]
I'm just keeping things up to date. Old dependencies cause dupes in the dependency tree, bloating compilation times and executable sizes.

**Comment by jonhoo** [comment]
@Detegr Could you issue a new point release for `ctrlc` (so like `3.1.4`) so that users can get the new version of nix without having to use a git dependency on `master`? I _think_ it's a backwards compatible change and so only a point release should be necessary?

**Comment by Detegr** [comment]
Sure, sorry I forgot to do that. `3.1.4` is out now.

**Comment by jonhoo** [comment]
Beautiful, thank you!

**Pull request merged**
