### PR TITLE
Add a blocking method

### PR DESCRIPTION
**Pull request by LevitatingBusinessMan**

### CODE REVIEW

**Comment by Detegr** [comment]
I'd like to have some rationale for adding this method.

**Comment by LevitatingBusinessMan** [comment]
For when your program spawns of a bunch of threads, and you just want the main thread to wait for a SIGKILL.

Is that weird? I've seen a few examples of ctrlc in use where a channel was used for ctrlc's thread to send a message to the main thread as to achieve the same thing, but that's a bit of a hack.

Besides, I don't see how adding functionality can hurt. Sadly the internal methods are private so there's no way to have ctrlc block your current thread.

**Comment by Detegr** [comment]
I see the appeal, but usually you'd want the threads to exit cleanly before exiting, don't you? The example in the README is using a channel to basically achieve the same result.

**Comment by Detegr** [comment]
Closed as stale.

**Pull request closed without merging**
