### PR TITLE
Counter and channel implementations

### PR DESCRIPTION
**Pull request by Detegr**
These still need documentation and reducing the size of `unsafe` blocks. However, the functionality is there and I haven't found any bugs. I've tested the implementation on Linux, Windows, and FreeBSD.

### CODE REVIEW

**Comment by Icelk** [comment]
Hi! Great project. Are there any updates on this?

**Comment by Detegr** [comment]
If I recall correctly this branch worked okay last time I checked but I lack the courage to publish this as a new version because this is a widely used crate by now and I'm afraid I'm doing something stupid unless I get some code reviews for this. The code reviews may never happen, and it might be that I'll never release this branch. We will see.

**Comment by Icelk** [comment]
Don't hesitate to ask if there's anything I can do.

**Comment by Detegr** [comment]
Code reviews for this are highly appreciated to get this moving forward.

**Comment by nogira** [comment]
i just tested macos and all the examples work fine

**Comment by Detegr** [comment]
Close to three years with no proper code reviews, I'm closing this PR. I don't expect this to be ever merged in. There are good alternatives available if you need some fancier signal handling mechanisms.

**Pull request closed without merging**
