### PR TITLE
Polling free implementation using semaphores

### PR DESCRIPTION
**Pull request by henninglive**
Replace the spinloop with a semephore on both windows and Unix. We can use POSIX Semaphores on Unix since sem_post() is guaranteed to be safe to call from signal-handlers. So we avoid the problems mentioned in #6. On windows signal handlers run on their own thread, so we can use whatever synchronization primitives we want, but I use a semaphore consistency sake.

I believe this simpler and more light weight solution than the solution suggested in #12.

### CODE REVIEW

**Comment by Detegr** [comment]
Thank you, I wasn't aware that POSIX Semaphores can actually be used from a signal handler. I need to carefully go through this PR before merging, I hope to have some free time during this week.

**Comment by Detegr** [comment]
This looks good. I'll change the error handling a bit and release new major version.

**Comment by henninglive** [comment]
What happened to issue #12, why is it not listed and why do get 404 when I try accessing the issue page. Has it been deleted or privated in some way? I have never seen this on github before, I thought there was no way to remove an issue.

**Comment by Detegr** [comment]
I have no idea, I was wondering the same thing myself.

**Comment by henninglive** [comment]
I think the user who posted the issue may have deleted their account.  This apparently also deletes all issues posted by them, which seems kind of stupid.


[github deleting-your-user-account](https://help.github.com/articles/deleting-your-user-account/)
> Recall that all repositories, forks of private repositories, wikis, issues, pull requests and pages owned by your account will be deleted, your billing will end, and your username will be available to anyone for use on GitHub.

**Comment by Detegr** [comment]
For some reason it became visible again so I managed to close it.

**Comment by joshtriplett** [comment]
I don't know why #12 didn't show up for a while; I'd guess transient github problems.  I certainly didn't delete anything.

**Comment by joshtriplett** [comment]
@Detegr Using a semaphore does indeed solve this problem, and eliminates the busyloop, which was my primary concern.  Sadly, it doesn't support providing a file descriptor for an event loop, but it does otherwise eliminate busylooping.

**Pull request merged**
