### PR TITLE
Update nix to 0.20

### PR DESCRIPTION
**Pull request by printfn**

### CODE REVIEW

**Comment by vincit-anttiker** [comment]
Is there a specific reason why there's a need to update `nix` to the latest version?

**Comment by Detegr** [comment]
Is there a specific reason why `nix` should be updated to the latest version?

**Comment by Fluhzar** [comment]
To throw my 2 cents in, one of `nix` dependencies is `cfg-if`. Specifically `nix v0.18` depends on `cfg-if v0.1`.

In one of my projects I also depend on `rand` which in turn depends on `cfg-if v1.0`. `nix v0.19` upgrades its `cfg-if` version to 1.0 as well.

Having separate versions in the dependency tree causes issues with, for example, generating documentation as both versions of `cfg-if` are named the same, but technically are different crates bc of the different versions, so `cargo doc` throws up a warning about it. So upgrading the version would resolve that clash.

This is a known issue within `cargo` and its tracking issue can be found [here](https://github.com/rust-lang/cargo/issues/6313).

My case is a rather knit-picky case and I can continue working just fine without the update, but to update the dependency would be a quality of life improvement in my workflow.

**Comment by Nukesor** [comment]
First of all, thanks for providing this library :)

I second @Fluhzar's statement. `nix 0.20` already got released and `ctrlc` is one of the main sources of duplicate dependencies in my projects. (duplicate `nix` version + duplicate `cfg-if` version).

It would be awesome if this PR could be updated to 0.20 and merged afterwards!

Stuff like this significantly reduces overall compile-time and at least I consider keeping dependencies up-to-date a best practice.


Thanks again for your time and effort maintaining this library!

Cheers

**Comment by Detegr** [comment]
Thanks for the comments and sorry for taking so long :)

**Pull request merged**
