### PR TITLE
Fix Windows code

### PR DESCRIPTION
**Pull request by retep998**

### CODE REVIEW

**Comment by Detegr** [comment]
Hi and thanks for the contribution!
I'm currently on a holiday without a development machine, so I'll check out this PR next week.

**Comment by Detegr** [comment]
Would it be reasonable to put winapi related crates under platform specific dependencies? Also, I would like to move platform specific `extern crate` declarations under the platform-specific `platform` module.

**Comment by retep998** [comment]
It would mean repeating all the Windows specific `Cargo.toml` dependencies at least 4 times for each of the Windows target triples. Since those crates are `#![cfg(windows)]` their effect on build times on non-windows is completely negligible. It would probably be better to wait for https://github.com/rust-lang/cargo/issues/1007 in order to make those dependencies platform specific.

**Comment by Detegr** [comment]
All right, I think it's fine to merge this then. Looking forward to see the that feature to be implemented in Cargo.

**Pull request merged**
