### PR TITLE
Update winapi to 0.3.4

### PR DESCRIPTION
**Pull request by debris**

### CODE REVIEW

**Comment by debris** [comment]
@Detegr rustfmt tests are terrible. They failed twice with different errors. The second failure is not even related with changes in this pr. What do I need to do, to make this pr merged? ;)

**Comment by Detegr** [comment]
This repo expects you to format the code with latest `rustfmt-nightly`. I know it is suboptimal as the way it formats changes over time and it might want to touch code that is not directly related. You can always open a new PR with rustfmt changes only. I'll format the repo to see whether this applies after that.

**Comment by Detegr** [comment]
Uh oh, that resulted in conflicts, sorry about that. Looks like `rustfmt` does not compile in Travis at the moment. If you can rebase master onto your PR I could merge this even though the test fails. Thanks!

**Comment by debris** [comment]
Thanks for the review @Detegr. I was on vacation for last several days. Merged master into my PR. Hope everything is fine now ;)

**Comment by Detegr** [comment]
Thanks!

**Pull request merged**
